### ISSUE TITLE
自行增添新的汉化文本后运行报错

### ISSUE THREAD

**Issue by fatinghenji** [GEEKiDoS/umamusume-localify#10]
运行的log如下：
![image](https://user-images.githubusercontent.com/37131177/121178836-88734180-c891-11eb-8618-4e87220bbcd5.png)
报错提示如下：
![image](https://user-images.githubusercontent.com/37131177/121178666-59f56680-c891-11eb-972b-993402d19f8d.png)
选择debug后报错如下：
![image](https://user-images.githubusercontent.com/37131177/121178758-75607180-c891-11eb-8f5e-9b251a09680b.png)
我增添的机翻汉化如下：
[chara.zip](https://github.com/GEEKiDoS/umamusume-localify/files/6616114/chara.zip)
请求解决错误

**Comment by GEEKiDoS** [comment]
用VSCode编辑Json 用VSCode编辑Json 用VSCode编辑Json
![image](https://user-images.githubusercontent.com/14933408/121179141-f0c22300-c891-11eb-9b34-3124e22c761c.png)
