### ISSUE TITLE
No OSS License

### ISSUE THREAD

**Issue by wx257osn2** [GEEKiDoS/umamusume-localify#19]
This is AWESOME work! I love this.
BTW, currently the source codes of this project has been published, but this project isn't licensed by any OSS license.
In GitHub, [no license project can be cloned by people who are not the repository owner, but must not be changed by them](https://docs.github.com/en/github/site-policy/github-terms-of-service#5-license-grant-to-other-users).
So, in the license term, currently we can't contribute to this project like PR.
However I understand that you are welcoming to some PR, so I propose you to license this project with some OSS license.

**Comment by GEEKiDoS** [comment]
Added fa865c5b6c0be3dbe99bae88683ffb02a3d088ab
