### ISSUE TITLE
This is a question about dumpStaticEntries in the config.json command.

### ISSUE THREAD

**Issue by ghost** [GEEKiDoS/umamusume-localify#27]
Hello. I am using it well.

If you use the config.json command dumpStaticEntries true
It is created in the dump.txt file, the problem is generated up to line 2645.
I'd like to analyze and check, but it's not easy.

Is it possible to change it to display until after line 2645?
Thanks for providing!

**Comment by GEEKiDoS** [comment]
Can you try to compile lastest code in repo and test with it?
I changed the static entry dumper behavior few months ago but I didn't upload a new release.

To compile this you just need Visual Studio 2019 (with c++ compiler)
Then clone repo with  `git clone https://github.com/GEEKiDoS/umamusume-localify.git --recursive` and run `generate.bat` to create project.
After that you can just just open vs solution in the `build` folder then compile it

**Comment by ghost** [comment]
Wow, thank you so much. I did as described and got the result.
Thank you for answer!
