### ISSUE TITLE
大佬有考虑为2k适配21：9比例的带鱼屏吗

### ISSUE THREAD

**Issue by lmh779601179** [GEEKiDoS/umamusume-localify#3]
目前我打开2K选项后就出现UI过宽，鼠标点击位置和实际不同，呈现水平偏移，通过修改UI参数也改变不了鼠标点击偏移的情况

**Comment by GEEKiDoS** [comment]
这个其实已经修好了 没有推送上来 我推送一下

**Comment by GEEKiDoS** [comment]
请下载 https://github.com/GEEKiDoS/umamusume-localify/releases/tag/test6 测试

**Comment by ZhangZong8598** [comment]
我是2560x1080的21:9,下载了之后也改了全屏,但横屏的live还是窗口化。是适配的是竖版的21：9吗？

**Comment by GEEKiDoS** [comment]
我没有21:9的显示器给我调试 你可以给我送个过来我就能试（bushi------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月3日(星期四) 晚上10:25
***@***.***&gt;;
***@***.***&gt;;&quot;State ***@***.***&gt;;
主题:&nbsp;Re: [GEEKiDoS/umamusume-localify] 大佬有考虑为2k适配21：9比例的带鱼屏吗 (#3)
