### ISSUE TITLE
umamusume-localify/resources/original_data/static.json 序號無法正常配對

### ISSUE THREAD

**Issue by yotv2000tw** [GEEKiDoS/umamusume-localify#30]
以下內容取自 `umamusume-localify/resources/original_data/static.json` 
```json
{
    "2639": "目覚まし時計を使用してコンティニューしますか？",
    "2640": "・枠番が再抽選されます",
    "2641": "・次のレースに限り、やる気が一段階アップします",
    "2642": "絶好調の場合はアップしません",
    "2643": "1日1回消費なし！",
    "2644": "現在お休みはできません",
    "2645": "お休み＆お出かけ確認",
    "2646": "お休みしてお出かけしますか？",
    "2647": "ターンを消費します",
    "2648": "体力が回復し、やる気が1段階アップします"
}
```
根據這個序號進行翻譯並且導入後，將會錯位到育成馬娘選單中的「おまかせ選択」按鈕名稱以及其按鈕的部分內容之中，這部分透過dump輸出後也會顯示為未翻譯的文本，原因我也不知道（沒研究）
![位置示意](https://user-images.githubusercontent.com/51760140/131139209-dde8768e-7ba0-4c01-9481-e1a583ced7f3.png)

最終仍要透過dump輸出的序號進行補正，而本部分的original內的序號也不知道到底對應到哪了，我在育成中使用鬧鐘時也未見其正常套用此處翻譯，修正依據dump的序號如下，也有成功對應（原本的「おまかせ選択」按鈕我還沒翻譯，剛剛無聊玩一下罷了）

```json
{
    "6596899330896709172": "確認任意選擇",
    "16155481676937896407": "請問是否要將現在的選擇重置\n並同時選擇所有的繼承馬娘？",
    "7303221236900109697": "包含租借馬娘",
    "11525592741652038301": "<color=#ff4400>使用租借將會消耗金幣</color>",
    "1096894875192618077": "<color=#ff4400>使用租借將會消耗金幣</color>"
}
```

![修正示意](https://user-images.githubusercontent.com/51760140/131139245-2498af30-7598-4544-a9d2-3df819e5454f.png)

而這個`static.json`也有不少地方發生這類型的狀況，不知道 `umamusume-localify/resources/original_data/` 這個資料夾內的文檔是怎麼導出來的...因為我用dump輸出的內容都不是這種四位數序號，而是很長串的那種，而這部分又常常沒對應
反正就是這幾天玩弄這個東西後發現的小問題

而我剛剛也有去看 [小修改#15](https://github.com/GEEKiDoS/umamusume-localify/pull/15) ，發現他們有針對這部分進行更動，也就是基於 `umamusume-localify/resources/original_data/static.json` 進行序號對應，不知道他們有沒有同樣的狀況發生，不然這個序號對應是完全錯位的感覺

**Comment by GEEKiDoS** [comment]
这个序号游戏版本一更新就会变
不知道有什么好的方法可以解决这个问题

**Comment by yotv2000tw** [comment]
> 
> 
> 这个序号游戏版本一更新就会变
> 不知道有什么好的方法可以解决这个问题

譬如每次更新後就針對上次的原始檔案來跟本次的dump去做橫向比對之類的嗎
我這次抓了一下確實 `static.json` 很大一部分都對不上了，要先從 `dump.txt` 去抓原文，然後跑回去搜尋之後發現從哪個序號變成哪個序號，接著再跑到翻譯文本的檔案去把序號重新調整...
我想的方法也只是把我的這套流程自動化而已(x

**Comment by AirJerryWhite** [comment]
我自己制作了一个工具应对这种情况，已经放在Readme里面了。

**Comment by yotv2000tw** [comment]
> 
> 
> 我自己制作了一个工具应对这种情况，已经放在Readme里面了。

太好了，感謝
