### ISSUE TITLE
使用Release後無法開啟遊戲

### ISSUE THREAD

**Issue by Narc17** [GEEKiDoS/umamusume-localify#4]
我試著把第五個版本的Release解壓縮放到遊戲資料夾, 但沒辦法開啟遊戲, 只要移走Release中的version.dll就可以開啟遊戲; DMM客戶端和遊戲都有設定使用管理員權限打開.

本人是使用筆記本用完全獨顯模式在跑(就是NVIDIA控制面板跟桌上型電腦是一樣), 筆記本的CPU是最新Intel 11代的CPU, 不知道是不是跟這有闗呢? 另外除了安裝遊戲外還有需要裝其他軟件才能使用這Release嗎? 這是新的筆記本, 就只有安裝DirectX, 跟所有相關的驅動程式.

感謝!

**Comment by GEEKiDoS** [comment]
是不是沒有安裝 Visual C++ Runtime 2019 運行庫




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GEEKiDoS/umamusume-localify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月28日(星期五) 凌晨2:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[GEEKiDoS/umamusume-localify] 使用Release後無法開啟遊戲 (#4)





 
我試著把第五個版本的Release解壓縮放到遊戲資料夾, 但沒辦法開啟遊戲, 只要移走Release中的version.dll就可以開啟遊戲; DMM客戶端和遊戲都有設定使用管理員權限打開.
 
本人是使用筆記本用完全獨顯模式在跑(就是NVIDIA控制面板跟桌上型電腦是一樣), 另外筆記本的CPU是最新Intel 11代的CPU, 不知道是不是跟這有闗呢? 另外除了安裝遊戲外還有需要裝其他軟件才能使用這Release嗎? 這是新的筆記本, 就只有安裝DirectX, 跟所有相關的驅動程式.
 
感謝!

**Comment by Narc17** [comment]
我剛測試過了, 看來真的是沒有裝Visual C++ Runtime 2019 運行庫, 感謝~!

我建議可以在readme那邊提醒一下需要裝Visual C++ Runtime 2019 運行庫，以便有人跟我一樣沒裝用不到。

謝謝解答！

**Comment by fatinghenji** [comment]
遇到相同的问题，运行库全部安装了
![image](https://user-images.githubusercontent.com/37131177/121053216-b4d58200-c7ed-11eb-9484-d22bad9b38ab.png)
![image](https://user-images.githubusercontent.com/37131177/121053259-bef78080-c7ed-11eb-94c8-53fe7fbb9f7c.png)

**Comment by GEEKiDoS** [comment]
> 遇到相同的问题，运行库全部安装了
> ![image](https://user-images.githubusercontent.com/37131177/121053216-b4d58200-c7ed-11eb-9484-d22bad9b38ab.png)
> ![image](https://user-images.githubusercontent.com/37131177/121053259-bef78080-c7ed-11eb-94c8-53fe7fbb9f7c.png)

2019 x64的没装 建议仔细看看
