### ISSUE TITLE
配置文件缺少uiScale字段会导致错误

### ISSUE THREAD

**Issue by natsusue** [GEEKiDoS/umamusume-localify#5]
`ssertion failed!
Program: D:program\DMMGamePlayer\Umamusume\VERSION.dllFile: D:krepo\umamusume-localifyidepsjrapidjson\...!document.hLine: 1800
Expression: lsNumber(
For information on how your program can cause an assertionfailure, see the visual C++ documentation on asserts
(Press Retry to debug the application - JIT must be enabled)`

可以持续复现
是否考虑过在读取config时添加默认值呢

**Comment by GEEKiDoS** [comment]
不考虑，你删他干甚么------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月30日(星期天) 凌晨1:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[GEEKiDoS/umamusume-localify] 配置文件缺少uiScale字段会导致错误 (#5)
