### ISSUE TITLE
关于改变分辨率的功能的问题

### ISSUE THREAD

**Issue by RabberDakk** [GEEKiDoS/umamusume-localify#7]
It's a magical tool! I struggled with a screen that is too small for me. Thank you so much :sob:
I have a question, if you don't mind, could you please tell me?

- Resolution is set to the same as the display resolution? (like 3840x2160 for a 4K monitor, 7680x4320 for an 8K monitor)
- Is there any difference in game resolution between `autoFullscreen: true` and `autoFullscreen: false` in same resolution monitor?
- If I play in landscape mode with `autoFullscreen: true` and then switch back to portrait mode, it returns to window mode, does the resolution of the game change?

**Comment by GEEKiDoS** [comment]
The resolution will be always set to your desktop resolution

**Comment by RabberDakk** [comment]
Thanks!
